[package]
name = "scaphandre"
version = "0.3.0"
authors = ["Benoit Petit <bpetit@hubblo.org>"]
edition = "2018"
license = "Apache-2.0"
description = "Electrical power consumption measurement agent."
repository = "https://github.com/hubblo-org/scaphandre"
readme = "README.md"
homepage = "https://hubblo-org.github.io/scaphandre-documentation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loggerv = "0.7.2"
log = "0.4"
clap = "2.33.3"
regex = "1"
procfs = "0.8.1"
riemann_client = { version = "0.9.0", optional = true }
hostname = "0.3.1"
protobuf = "2.20.0"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
warp10 = { version = "1.0.0", optional = true }
time = "0.2.25"
colored = "2.0.0"
chrono = "0.4.19"
rs-docker = { version = "0.0.58", optional = true }
hyper = { version = "0.14", features = ["full"], optional = true }
tokio = { version = "1", features = ["full"]}
#rs-docker = { path = "../rust-docker" }

[features]
default = ["prometheus", "riemann", "warp10", "containers", "json"]
prometheus = ["hyper"]
riemann = ["riemann_client"]
json = ["serde", "serde_json"]
containers = ["rs-docker"]