version: '3.2'

services:

  scaphandre:
    image: scaphandre-dev
    ports: 
      - "8089:8080"
    volumes:
      - type: bind
        source: /proc
        target: /proc
      - type: bind
        source: /sys/class/powercap
        target: /sys/class/powercap
    command: ["prometheus"]                         
    networks:
      - scaphandre-network
    
  prometheus:
    build:
      context: ./prom
    ports: 
      - "9099:9090"
    volumes: 
      - promdata-scaphandre:/prometheus 
    networks:
      - scaphandre-network

volumes:
  promdata-scaphandre:

networks:
  scaphandre-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.33.0/24
