name: build_and_test

on:
  push:
    branches: [ ci/#43-add-cargo-test-all-in-ci ]
  pull_request:
    branches: [ ci/#43-add-cargo-test-all-in-ci ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build_and_test_x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies (awxkit)
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: Install python requirements (awxkit)
        run: |
          python -m pip install --upgrade pip
          pip install awxkit
          #- name: Install jq
          #  run: |
          #    sudo apt install jq -y
      - name: Log on AWX 
        id: login
        run: |
          export AWX_TOKEN=$(awx --conf.host ${{ secrets.AWX_HOST }} --conf.username ${{ secrets.AWX_USERNAME }} --conf.password ${{ secrets.AWX_PASSWORD }} login | jq .token | tr -d '"')
          echo "::set-output name=awx_token::${AWX_TOKEN}"
      - name: Launch job
        id: launch
        run: |
          awx --conf.token ${{ steps.login.outputs.awx_token }} --conf.host https://cd.hubblo.org job_templates launch --extra_vars="{\"github_repository\":\"${{ env.GITHUB_REPOSITORY }}\",\"github_actor\":\"${{ env.GITHUB_ACTOR }}\",\"github_workflow\":\"${{ env.GITHUB_WORKFLOW }}\",\"github_workspace\":\"${{ env.GITHUB_WORKSPACE }}\",\"github_event_name\":\"${{ env.GITHUB_EVENT_NAME }}\",\"github_event_path\":\"${{ env.GITHUB_EVENT_PATH }}\",\"github_sha\":\"${{ env.GITHUB_SHA }}\",\"github_ref\":\"${{ env.GITHUB_REF }}\",\"github_head_ref\":\"${{ env.GITHUB_HEAD_REF }}\",\"github_base_ref\":\"${{ env.GITHUB_BASE_REF }}\",\"github_server_url\":\"${{ env.GITHUB_SERVER_URL }}\"}" 9 --wait
