name: build_and_test

on:
  push:
    branches: [ ci/#43-add-cargo-test-all-in-ci ]
  pull_request:
    branches: [ ci/#43-add-cargo-test-all-in-ci ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build_and_test_x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies (awxkit)
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
        run: |
          python -m pip install --upgrade pip
          pip install awxkit
      - name: Install jq
        run: |
          apt install jq -y
      - name: Log on AWX 
        id: login
        run: |
          export AWX_TOKEN=$(awx --conf.host ${{ secrets.AWX_HOST }} --conf.username ${{ secrets.AWX_USERNAME }} --conf.password ${{ secrets.AWX_PASSWORD }} login | jq .token | tr -d '"')
          echo "::set-output name=awx_token::${AWX_TOKEN}"
      - name: Launch job
        id: launch
        run: |
          awx --conf.token ${{ steps.login.outputs.awx_token }} --conf.host https://cd.hubblo.org job_templates launch --extra_vars="{\"github_repository\":\"coucou/repo\",\"github_actor\":\"bpetit\"}" 9 --wait | jq
