name: Build exe installer for windows for prometheus-push only version

on:
  push:
    paths-ignore:
      - 'docs_src/**'
      - 'README.md'
      - 'CITATION'
      - 'book.toml'
      - 'CONTRIBUTING.md'
    tags: [ 'v*.*.*', 'dev*.*.*' ]
    branches: [ '311-github-workflow-to-build-and-publish-a-exemsi-file-including-signed-rapl-driver-at-each-tagrelease' ]

jobs:
  build_exe_win1011:
    name: Build exe installer for windows 10/11/server 2016/server 2019/server 2022
    runs-on: "windows-2019"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: scaphandre
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: hubblo-org/windows-rapl-driver.git
          ref: master
          path: windows-rapl-driver
      - name: Install Innosoft
        run: |
          $url = "https://jrsoftware.org/download.php/is.exe"
          $dest = "is.exe"
          Invoke-WebRequest -Uri $url -OutFile $dest
          ls
          & "$dest" /verysilent /suppressmsgbox
          ls "C:\Program Files (x86)\"
      - name: Install Rustup
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install rustup.install --ignore-checksums
      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable-x86_64-pc-windows-msvc
      - name: Build (debug mode)
        run: |
          cargo build --release --no-default-features --features "prometheuspush json"